#include "scene.h"

class IntersectionNode
{
public:
	vec3 pos;
	vec3 normal;
	vec3 view;
	SceneObject *hit;
	PointMaterial *mat;
	IntersectionNode *reflect;
	IntersectionNode *refract;
	vec3 outColor;

	//intersect with the scene and spawn child rays
	IntersectionNode(vec3 &ro, vec3 &rd)
	{
		view = rd;
		float nearest = -1.0;
		float d=0.0;
		for (int i=0; i<sceneNumObjects; i++) {
			d = sceneObjectList[i]->intersect(ro,rd);
			if (d<nearest || nearest==-1.0) {
				nearest = d;
				hit = sceneObjectList[i];
			}
		}
		if (nearest==-1.0) { //No intersection
			mat = new PointMaterial(vec3(0.6,0.6,0.9));
		} else {
			pos = ro + rd*d;
			mat = hit->materialAt(pos);
			normal = hit->normalAt(pos);
		}
		defaultLighting(); // perform non-photon mapping lighting
	}

	void defaultLighting()
	{
		outColor = vec3(0.0);
	}

	//return the color generated by this intersection and children
	vec3 calculateColor()
	{
		return mat->diffuse;
	}
};

class IntersectionTree
{
public:
	IntersectionNode *head;
	
	IntersectionTree(float x, float y)
	{
		x = 2*(x-0.5);
		y = 2*(y-0.5);
		vec3 ro = vec3(0.0,0.0,-5.0);
		vec3 rd = vec3(x,y,-4.0)-ro;
		head = new IntersectionNode(ro,rd);
	}

	vec3 render() { return head->calculateColor(); }
};